name: Proof HTML

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Proof HTML
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
